* Testcase
** Auxiliary Functions
#+begin_src c++
/**
 * @brief get_a_target_long
 *
 * get a long number from the console
 * 
 * @return long
 * 
 * @note Optional note
 */

long get_a_target_long() {
  long target = 0;
  cout << "target (0~" << RAND_MAX << "): ";
  cin >> target;
  return target;
}

/**
 * @brief get_a_target_string
 *
 * get a string val from the console
 * 
 * @return string
 * 
 * @note Optional note
 */
string get_a_target_string() {
  long target = 0;
  char buf[10];

  cout << "target (0~" << RAND_MAX << "): ";
  cin >> target;
  snprintf(buf, 10, "%ld", target);
  return string(buf);
}

/**
 * @brief compareLongs
 *
 * compare two long type vals used for qsort and bsearch
 * 
 * @return int 1 if a > b 
 * 
 * @note Optional note
 */
int compareLongs(const void *a, const void *b) {
  return (*(long *)a - *(long *)b);
}

/**
 * @brief compareStrings
 *
 * compare two strings using the overload operator constructed
 * 
 * @param[in]  a
 * @param[out] b  
 * @return int 
 * 
 * @note Optional note
 */
int compareStrings(const void *a, const void *b) {
  if (*(string *)a > *(string *)b)
    return 1;
  else if (*(string *)a < *(string *)b)
    return -1;
  else
    return 0;
}
#+end_src

** array-test
#+begin_src c++
namespace zz01
{
  #define ASIZE 500000
  void test_array(){
    cout << "\ntest_array()......... \n";

    array<long, ASIZE> c;

    clock_t timestart = clock();
    for(long i = 0; i < ASIZE; i++){
      c[i] = rand();
    }

    cout << "milli-seconds : " << clock() - timestart << endl;
    cout << "array.size()  : " << c.size() << endl;
    cout << "array.front() : " << c.front() << endl;
    cout << "array.back()  : " << c.back() << endl;
    cout << "array.data()  : " << c.data() << endl;
    // get a target from console 
    long target = get_a_target_long();
    qsort(c.data(), ASIZE, sizeof(long), compareLongs);

    // bsearch but concern about the ASIZE and nmem size
    long *pItem = (long *)bsearch(&target, c.data(), ASIZE, sizeof(long), compareLongs);
    cout << "qsort + bsearch milli-seconds : " << clock() - timestart << endl;

    if(pItem != NULL)
      cout << "Found : " << *pItem << endl;
    else
      cout << "not Found! " << endl;
  }

}
#+end_src

Remember that, if you use bsearch, you have to give it a sequential array which means the arrays are consecutive in memory. And c.data() refered to the first element address.

** test_vector
#+begin_src c
namespace zz02
{
  void test_vector(long &value)
  {
    cout << "\ntest_vector()......... \n";
    vector<string> c;
    char buf[10];

    clock_t timeStart = clock();
    for(long i = 0; i < value; i++){
      try {
	snprintf(buf, 10, "%d", rand());
	c.push_back(string(buf));
      }
      catch(exception& p){
	// it may throw an exception of std::bad_alloc
	// that is because the vector allocates memory in order and copy
	// the old contents to the new memory
	cout << "i = " << i << " " << p.what() << endl;
	abort();
      }
    }
    cout << "milli-seconds : " << clock() - timeStart << endl;
    cout << "vector.size()  : " << c.size() << endl;
    cout << "vector.front() : " << c.front() << endl;
    cout << "vector.back()  : " << c.back() << endl;
    cout << "vector.data()  : " << c.data() << endl;
    cout << "vector.capacity()  : " << c.capacity() << endl;

    string target = get_a_target_string();

    timeStart = clock();
    auto pItem = ::find(c.begin(), c.end(), target);
    cout << "milli-seconds of ::find : " << clock() - timeStart << endl;

    timeStart = clock();
    ::sort(c.begin(), c.end());
    //reinterpret_cast<std::string*>
    string *pString = static_cast<string *>(bsearch(&target, c.data(), value, sizeof(string), compareStrings));
    //bsearch(const void *key, const void *base, size_t nmemb, size_t size, __compar_fn_t compar);
    cout << "milli-seconds of ::sort + bsearch : " << clock() - timeStart << endl;
    if(pString != NULL)
      cout << "Found : " << *pString << endl;
    else
      cout << "not Found! " << endl;
  }
}
#+end_src

Note that, if we don't cast the bsearch return type value into string *, it will give an error like below.
#+begin_src sh
stl_test.cc:154:31: error: invalid conversion from ‘void*’ to ‘std::string*’ {aka ‘std::__cxx11::basic_string<char>*’} [-fpermissive]
  154 |     string *pString = (bsearch(&target, c.data(), value, sizeof(string), compareStrings));
      |                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               |
      |                               void*
#+end_src
Another thing we need to know is that, if the container have an inner method like sort or find, we have to use these methods provided, in this way, the stl make the fast speed of the caller function.

Also, vector is sequentially in memory, it will allocate memory in large and copy the contents into the new memory.
And vector grows like pow(2,n), which means the speed is low in memory growth.
** test_list
#+begin_src c++
namespace zz03
{
  void test_list(long &value)
  {
    cout << "\ntest_list()......... \n";
    list<string> c;
    char buf[10];

    clock_t timeStart = clock();
    for(long i = 0; i < value; i++){
      try {
	snprintf(buf, 10, "%d", rand());
	c.push_back(string(buf));
      }
      catch(exception& p){
	// it may throw an exception of std::bad_alloc
	// that is because the vector allocates memory in order and copy
	// the old contents to the new memory
	cout << "i = " << i << " " << p.what() << endl;
	abort();
      }
    }
    cout << "milli-seconds : " << clock() - timeStart << endl;
    cout << "list.size()  : " << c.size() << endl;
    cout << "list.front() : " << c.front() << endl;
    cout << "list.back()  : " << c.back() << endl;
    cout << "list.max_size()  : " << c.max_size() << endl;

    string target = get_a_target_string();
    timeStart = clock();
    auto pItem = ::find(c.begin(), c.end(), target);
    cout << "milli-seconds of ::find : " << clock() - timeStart << endl;

    if(pItem != c.end())
      cout << "Found : " << *pItem << endl;
    else
      cout << "not Found! " << endl;

    timeStart = clock();
    c.sort();
    cout << "milli-seconds of list.sort : " << clock() - timeStart << endl;
  }
}
#+end_src

Actually, the list above is double-linked list, but not sequentially in memory, the list has no .data method, confirming that it is not sequentially in memory. Likewise, it has many inner methods like sort, insert, merge, etc. If you have some requests, try to use inner methods first before find the global methods.

** test_forwardlist

