* argument pass
- pass by value
- pass by reference (to const)
Advice: all arguments passed by reference, if it's not changed inside the function add *const* identifier.
Besides, in reality, the reference is a pointer.
#+begin_src c++

class complex
{
public:
  complex (double r= 0, double i= 0)
    : re(r), im(i)
    {}
    
  complex& operator+=(const complex&);
  double real() const{return re;}
  double imag() const{return im;}

private:
  double re, im;
  
  friend complex& __doapl (complex*, const complex&);
}

ostream&
operator << (ostream& os, const complex& x)
{
  return os << '(' << real(x) << ',' 
            << imag(x) << ')';
}

//...
complex c1(2,1);
complex c2;
cout << c1;
cout << c2 << c1;
#+end_src

* return value 
- return value
- return reference
Advice: all return value are set reference, if some cases happen that it's not allowed to return reference then return value.

* friend
#+begin_src c++
class complex
{
public:
  complex (double r= 0, double i= 0)
    : re(r), im(i)
    {}
    
  complex& operator+=(const complex&);
  double real() const{return re;}
  double imag() const{return im;}

private:
  double re, im;
  
  friend complex& __doapl (complex*, const complex&);
}

inline complex&
__doapl (complex* ths, const complex& r)
{
  ths->re += r.re;
  ths->im += r.im;
  return *ths;
}
#+end_src
friend function can access the private data.( direct access)
So we don't have to add class scope operator before the definition of the friend function.

Another example,
*objects belong to the same classs are friend each other*.
#+begin_src c++
class complex
{
public:
  complex (double r = 0, double i = 0)
    : re(r), im(i)
     {}
  int func(const comple& param)
  { return param.re + param.im; }

private:
  double re, im;
};

//.....
{
  complex c1(2,1);
  complex c2;
  c2.func(c1);
}
#+end_src

* Good Class

1. data are all put into private access level
2.pass arg by reference (to const)
3.return by reference
4.const member function
5.ctor initialization list(*:*)

* Function Definition
when to pass by reference, when to return by reference
Let's see the argument pass procedure.
There are two cases, 
1. the first arg will be changed, and the second won't change, actually the we have space to store the changed value, then we return by reference like *+=*.
2. we don't have allocated space to store the changed value, then we have to allocate memory on stack, and return by value. like *+*.
   
example:
#+begin_src c++
inline complex&
__doapl( complex *ths, const complex& r)
{
  ths->re += r.re;
  ths->im += r.im;
  return *ths; // we actually have space to store.
}

inline complex&
complex::operator += (const complex& r)
{
  return __doapl(this, r);
}
#+end_src
