#+TITLE: 3-operator-overload-object-oriented-cpp
#+DATE: 2025-03-30 11:06:23 +0800>
#+HUGO_DRAFT: false
#+HUGO_CATEGORIES: object_oriented
#+HUGO_TAGS: c++ language
#+HUGO_CUSTOM_FRONT_MATTER: :showtoc true
* operator overload
** member function
the member function overload contains this pointer implicitly, but you don't have to pass the argument. you can use it freely.
#+begin_src c++
inline complex&
__doapl(complex* ths, const complex& r)
{
  ths->re += r.re;
  ths->im += r.im;
  return *ths;
}

inline complex&
complex::operator += (const complex& r)
{
  return __doapl(this, r);
}


//... 
complex c1(2,1);
complex c2(5);
c2 += c1;
c3 += c2 += c1;

#+end_src

why we need return by reference when we define *+=* overload function? If you just use c2 += c1; you can define void return type, but when there is a consecutive assignment which means the expression must return a type that can be passed to another +=. So *complex &* matters. *c3 += c2 += c1*

** non-member function (global function)
There is no *this* pointer, it belongs to global function.
#+begin_src c++
inline complex operator + (const complex &x, const complex &y)
{
  return complex (real(x) + real(y), imag(x) + imag(y));
}

inline complex operator + (const complex &x, double y)
{
  return complex (real(x) + y, imag(x));
}

inline complex operator + (double x, const complex &y)
{
  return complex (x + real(y) , imag(y));
}

//...
complex c1(2,1);
complex c2;

c2 = c1 + c2;
c2 = c1 + 5;
c2 = 7 + c1;
#+end_src

Besides, it used *temp object*--- *typename()*.There is no allocated storage provided, you have to return by value by creating a local object.

Other definitions outside the class.
#+begin_src c++
inline complex  //inline complex& ok
operator + (const complex &x)
{
  return x;
} 
inline complex 
operator - (const complex &x)
{
  return complex(-real(x), -imag(x));
} 
#+end_src

There is another question remaining that in +(positive function), there isn't newer things created, you can return by reference.

Another example:
#+begin_src c++
inline complex
conj (const complex & x)
{
  return complex( real(x), -imag(x));
}

#include <iostream>
ostream&
operator << (ostream &os, const complex& x)
{
  return os << '(' << real(x) << ','
            << imag(x) << ')';
}
complex c1(2,1)
cout << conj(c1)
cout << c1 << conj(c1);
#+end_src

The operator<< overload function must be non-member function, because the complex is new than ostream and the first parameter is always an ostream object. It would have to be a member of the ostream class but we can not change).
And << left operand is cout, right operand is complex x; return by reference is for sure in case of consecutive usage.

